export const PURE_TAB_HEIGHT = 52;

export const DEFAULT_HEADER_HEIGHT = 52;

export const TAB_BAR_HEIGHT = 112;

export const TAB_BAR_STORY_PLAYER_HEIGHT = 56;

export const FILTERS_SCREEN_BUTTONS_AREA = 66;

export const MODAL_CONTENT_HEIGHT = 'CONTENT_HEIGHT';
