import { SortConfig } from '@/hooks/database/useStories';

export type StoryCoverType = 'small' | 'medium' | 'full';

export const POPULAR_STORIES_FILTER = 'is_coming_soon = false';

export const POPULAR_STORIES_CONFIG: SortConfig[] = [
  {
    reverse: true,
    sortDescriptor: 'played_count',
  },
];

export const FEATURING_STORIES_FILTER = 'is_featuring = true';

export const FEATURING_STORIES_CONFIG: SortConfig[] = [
  {
    reverse: false,
    sortDescriptor: 'is_coming_soon',
  },
  {
    reverse: false,
    sortDescriptor: 'played_count',
  },
];

export const FREE_STORIES_FILTER = 'is_free = true';

export enum CATEGORY_IDS {
  CLASSIC_TRANSFORMATIONS = 1,
  FOREST_ADVENTURES,
  MAGICAL_JOURNEYS,
  KINGDOMS_AND_CASTELS,
  MYSTERIES_AND_ENIGMAS,
  HEROIC_TALES,
  ANIMAL_TALES,
  TALES_OF_LOVE_AND_FRIENDSHIP,
  TALES_OF_MAGICAL_OBJECTS,
  TALES_OF_WIZARDS_AND_WITCHES,
  TALES_OF_OVERCOMING,
  MAGICAL_CREATURES_AND_HELPERS,
}

export enum CATEGORY_NAMES {
  ANIMAL_TALES = 'Animal Tales',
  CLASSIC_TRANSFORMATIONS = 'Classic Transformations',
  FOREST_ADVENTURES = 'Forest Adventures',
  HEROIC_TALES = 'Heroic Tales',
  KINGDOMS_AND_CASTELS = 'Kingdoms and Castles',
  MAGICAL_CREATURES_AND_HELPERS = 'Magical Creatures and Helpers',
  MAGICAL_JOURNEYS = 'Magical Journeys',
  MYSTERIES_AND_ENIGMAS = 'Mysteries and Enigmas',
  TALES_OF_LOVE_AND_FRIENDSHIP = 'Tales of Love and Friendship',
  TALES_OF_MAGICAL_OBJECTS = 'Tales of Magical Objects',
  TALES_OF_OVERCOMING = 'Tales of Overcoming',
  TALES_OF_WIZARDS_AND_WITCHES = 'Tales of Wizards and Witches',
}

export const MAP_CATEGORY_ID_TO_NAMES = {
  [CATEGORY_IDS.CLASSIC_TRANSFORMATIONS]: CATEGORY_NAMES.CLASSIC_TRANSFORMATIONS,
  [CATEGORY_IDS.FOREST_ADVENTURES]: CATEGORY_NAMES.FOREST_ADVENTURES,
  [CATEGORY_IDS.MAGICAL_JOURNEYS]: CATEGORY_NAMES.MAGICAL_JOURNEYS,
  [CATEGORY_IDS.KINGDOMS_AND_CASTELS]: CATEGORY_NAMES.KINGDOMS_AND_CASTELS,
  [CATEGORY_IDS.MYSTERIES_AND_ENIGMAS]: CATEGORY_NAMES.MYSTERIES_AND_ENIGMAS,
  [CATEGORY_IDS.HEROIC_TALES]: CATEGORY_NAMES.HEROIC_TALES,
  [CATEGORY_IDS.ANIMAL_TALES]: CATEGORY_NAMES.ANIMAL_TALES,
  [CATEGORY_IDS.TALES_OF_LOVE_AND_FRIENDSHIP]: CATEGORY_NAMES.TALES_OF_LOVE_AND_FRIENDSHIP,
  [CATEGORY_IDS.MAGICAL_CREATURES_AND_HELPERS]: CATEGORY_NAMES.MAGICAL_CREATURES_AND_HELPERS,
  [CATEGORY_IDS.TALES_OF_MAGICAL_OBJECTS]: CATEGORY_NAMES.TALES_OF_MAGICAL_OBJECTS,
  [CATEGORY_IDS.TALES_OF_OVERCOMING]: CATEGORY_NAMES.TALES_OF_OVERCOMING,
  [CATEGORY_IDS.TALES_OF_WIZARDS_AND_WITCHES]: CATEGORY_NAMES.TALES_OF_WIZARDS_AND_WITCHES,
};
