import { SortConfig } from '@/hooks/database/useStories';

export type StoryCoverType = 'small' | 'medium' | 'full';

export const POPULAR_STORIES_FILTER = 'is_coming_soon = false';

export const POPULAR_STORIES_CONFIG: SortConfig[] = [
  {
    reverse: true,
    sortDescriptor: 'played_count',
  },
];

export const FEATURING_STORIES_FILTER = 'is_featuring = true';

export const FEATURING_STORIES_CONFIG: SortConfig[] = [
  {
    reverse: false,
    sortDescriptor: 'is_coming_soon',
  },
  {
    reverse: false,
    sortDescriptor: 'played_count',
  },
];

export const FREE_STORIES_FILTER = 'is_free = true';

export enum CATEGORY_IDS {
  CLASSIC_TRANSFORMATIONS = 1,
  FOREST_ADVENTURES,
  MAGICAL_JOURNEYS,
  KINGDOMS_AND_CASTELS,
  MYSTERIES_AND_ENIGMAS,
  HEROIC_TALES,
  ANIMAL_TALES,
  TALES_OF_LOVE_AND_FRIENDSHIP,
  TALES_OF_MAGICAL_OBJECTS,
  TALES_OF_WIZARDS_AND_WITCHES,
  TALES_OF_OVERCOMING,
  MAGICAL_CREATURES_AND_HELPERS,
}

export enum CATEGORY_KEYS {
  ANIMAL_TALES = 'ANIMAL_TALES',
  CLASSIC_TRANSFORMATIONS = 'CLASSIC_TRANSFORMATIONS',
  FOREST_ADVENTURES = 'FOREST_ADVENTURES',
  HEROIC_TALES = 'HEROIC_TALES',
  KINGDOMS_AND_CASTELS = 'KINGDOMS_AND_CASTELS',
  MAGICAL_CREATURES_AND_HELPERS = 'MAGICAL_CREATURES_AND_HELPERS',
  MAGICAL_JOURNEYS = 'MAGICAL_JOURNEYS',
  MYSTERIES_AND_ENIGMAS = 'MYSTERIES_AND_ENIGMAS',
  TALES_OF_LOVE_AND_FRIENDSHIP = 'TALES_OF_LOVE_AND_FRIENDSHIP',
  TALES_OF_MAGICAL_OBJECTS = 'TALES_OF_MAGICAL_OBJECTS',
  TALES_OF_OVERCOMING = 'TALES_OF_OVERCOMING',
  TALES_OF_WIZARDS_AND_WITCHES = 'TALES_OF_WIZARDS_AND_WITCHES',
}

export const MAP_CATEGORY_ID_TO_KEYS = {
  [CATEGORY_IDS.CLASSIC_TRANSFORMATIONS]: CATEGORY_KEYS.CLASSIC_TRANSFORMATIONS,
  [CATEGORY_IDS.FOREST_ADVENTURES]: CATEGORY_KEYS.FOREST_ADVENTURES,
  [CATEGORY_IDS.MAGICAL_JOURNEYS]: CATEGORY_KEYS.MAGICAL_JOURNEYS,
  [CATEGORY_IDS.KINGDOMS_AND_CASTELS]: CATEGORY_KEYS.KINGDOMS_AND_CASTELS,
  [CATEGORY_IDS.MYSTERIES_AND_ENIGMAS]: CATEGORY_KEYS.MYSTERIES_AND_ENIGMAS,
  [CATEGORY_IDS.HEROIC_TALES]: CATEGORY_KEYS.HEROIC_TALES,
  [CATEGORY_IDS.ANIMAL_TALES]: CATEGORY_KEYS.ANIMAL_TALES,
  [CATEGORY_IDS.TALES_OF_LOVE_AND_FRIENDSHIP]: CATEGORY_KEYS.TALES_OF_LOVE_AND_FRIENDSHIP,
  [CATEGORY_IDS.MAGICAL_CREATURES_AND_HELPERS]: CATEGORY_KEYS.MAGICAL_CREATURES_AND_HELPERS,
  [CATEGORY_IDS.TALES_OF_MAGICAL_OBJECTS]: CATEGORY_KEYS.TALES_OF_MAGICAL_OBJECTS,
  [CATEGORY_IDS.TALES_OF_OVERCOMING]: CATEGORY_KEYS.TALES_OF_OVERCOMING,
  [CATEGORY_IDS.TALES_OF_WIZARDS_AND_WITCHES]: CATEGORY_KEYS.TALES_OF_WIZARDS_AND_WITCHES,
};
