/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#import "MNTShareManagerSpec.h"

@implementation RCTCxxConvert (NativeShareManager_ShareOptions)
+ (RCTManagedPointer *)JS_NativeShareManager_ShareOptions:(id)json
{
  return facebook::react::managedPointer<JS::NativeShareManager::ShareOptions>(json);
}
@end
namespace facebook {
  namespace react {
    
    static facebook::jsi::Value __hostFunction_NativeShareManagerSpecJSI_share(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, VoidKind, "share", @selector(share:), args, count);
    }

    NativeShareManagerSpecJSI::NativeShareManagerSpecJSI(const ObjCTurboModule::InitParams &params)
      : ObjCTurboModule(params) {
        
        methodMap_["share"] = MethodMetadata {1, __hostFunction_NativeShareManagerSpecJSI_share};
        setMethodArgConversionSelector(@"share", 0, @"JS_NativeShareManager_ShareOptions:");
    }
  } // namespace react
} // namespace facebook
