export const commonLocalization = {
  en: {
    back: 'Back',
    chooseATale: 'Choose a tale',
    close: 'Close',
    comingSoon: 'Coming soon',
    continue: 'Continue',
    createYourFairytale: 'Create your fairytale',
    createYourVoice: 'Create your voice',
    free: 'Free',
    min: 'min',
    moonlit: 'Moonlit',
    moonlitFairytaleAtmosphere: 'Create a magical, fairytale\natmosphere',
    moreMoonlitTalesComingSoon: 'More Moonlit tales\ncoming soon',
    noResultForSearch: 'No results\nfor this prompt',
    popularSearch: 'Popular search',
    privacy: 'Privacy',
    readTalesInYourOwnVoice: 'Read tales in\nyour own voice',
    restore: 'Restore',
    saved: 'Saved',
    seeAll: 'See all',
    selectVoice: 'Select voice',
    skip: 'Skip',
    subscription: 'Subscription',
    terms: 'Terms',
    upgrade: 'Upgrade',
    voice: 'Voice',
  },
};
