export const commonLocalization = {
  en: {
    back: 'Back',
    close: 'Close',
    comingSoon: 'Coming soon',
    continue: 'Continue',
    free: 'Free',
    min: 'min',
    moreMoonlitTalesComingSoon: 'More Moonlit tales\ncoming soon',
    noResultForSearch: 'No results\nfor this prompt',
    popularSearch: 'Popular search',
    privacy: 'Privacy',
    restore: 'Restore',
    saved: 'Saved',
    seeAll: 'See all',
    selectVoice: 'Select voice',
    skip: 'Skip',
    subscription: 'Subscription',
    terms: 'Terms',
    upgrade: 'Upgrade',
    voice: 'Voice',
  },
};
