/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#import "MNTAudioPlayerSpec.h"

@implementation RCTCxxConvert (NativeAudioPlayer_SpecSetToPlayFileFileInfo)
+ (RCTManagedPointer *)JS_NativeAudioPlayer_SpecSetToPlayFileFileInfo:(id)json
{
  return facebook::react::managedPointer<JS::NativeAudioPlayer::SpecSetToPlayFileFileInfo>(json);
}
@end
namespace facebook {
  namespace react {
    
    static facebook::jsi::Value __hostFunction_NativeAudioPlayerSpecJSI_getCurrentState(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, ObjectKind, "getCurrentState", @selector(getCurrentState), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeAudioPlayerSpecJSI_pausePlaying(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, ObjectKind, "pausePlaying", @selector(pausePlaying), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeAudioPlayerSpecJSI_rewindPlayingToTime(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, VoidKind, "rewindPlayingToTime", @selector(rewindPlayingToTime:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeAudioPlayerSpecJSI_setToPlayFile(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, VoidKind, "setToPlayFile", @selector(setToPlayFile:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeAudioPlayerSpecJSI_startPlayingFromTime(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, VoidKind, "startPlayingFromTime", @selector(startPlayingFromTime:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeAudioPlayerSpecJSI_stopPlaying(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, VoidKind, "stopPlaying", @selector(stopPlaying), args, count);
    }
    static facebook::jsi::Value __hostFunction_NativeAudioPlayerSpecJSI_addListener(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, VoidKind, "addListener", @selector(addListener:), args, count);
    }

    static facebook::jsi::Value __hostFunction_NativeAudioPlayerSpecJSI_removeListeners(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
      return static_cast<ObjCTurboModule&>(turboModule).invokeObjCMethod(rt, VoidKind, "removeListeners", @selector(removeListeners:), args, count);
    }

    NativeAudioPlayerSpecJSI::NativeAudioPlayerSpecJSI(const ObjCTurboModule::InitParams &params)
      : ObjCTurboModule(params) {
        
        methodMap_["getCurrentState"] = MethodMetadata {0, __hostFunction_NativeAudioPlayerSpecJSI_getCurrentState};
        
        
        methodMap_["pausePlaying"] = MethodMetadata {0, __hostFunction_NativeAudioPlayerSpecJSI_pausePlaying};
        
        
        methodMap_["rewindPlayingToTime"] = MethodMetadata {1, __hostFunction_NativeAudioPlayerSpecJSI_rewindPlayingToTime};
        
        
        methodMap_["setToPlayFile"] = MethodMetadata {1, __hostFunction_NativeAudioPlayerSpecJSI_setToPlayFile};
        setMethodArgConversionSelector(@"setToPlayFile", 0, @"JS_NativeAudioPlayer_SpecSetToPlayFileFileInfo:");
        
        methodMap_["startPlayingFromTime"] = MethodMetadata {1, __hostFunction_NativeAudioPlayerSpecJSI_startPlayingFromTime};
        
        
        methodMap_["stopPlaying"] = MethodMetadata {0, __hostFunction_NativeAudioPlayerSpecJSI_stopPlaying};
        
        methodMap_["addListener"] = MethodMetadata {1, __hostFunction_NativeAudioPlayerSpecJSI_addListener};
        
        methodMap_["removeListeners"] = MethodMetadata {1, __hostFunction_NativeAudioPlayerSpecJSI_removeListeners};
        
    }
  } // namespace react
} // namespace facebook
