/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleCpp.js
 */

#include "MNTShareManagerSpecJSI.h"

namespace facebook {
namespace react {

static jsi::Value __hostFunction_NativeShareManagerCxxSpecJSI_share(jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value* args, size_t count) {
  static_cast<NativeShareManagerCxxSpecJSI *>(&turboModule)->share(
    rt,
    args[0].asObject(rt)
  );
  return jsi::Value::undefined();
}

NativeShareManagerCxxSpecJSI::NativeShareManagerCxxSpecJSI(std::shared_ptr<CallInvoker> jsInvoker)
  : TurboModule("MNTShareManager", jsInvoker) {
  methodMap_["share"] = MethodMetadata {1, __hostFunction_NativeShareManagerCxxSpecJSI_share};
}


} // namespace react
} // namespace facebook
