/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif
#import <Foundation/Foundation.h>
#import <RCTRequired/RCTRequired.h>
#import <RCTTypeSafety/RCTConvertHelpers.h>
#import <RCTTypeSafety/RCTTypedModuleConstants.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTCxxConvert.h>
#import <React/RCTManagedPointer.h>
#import <ReactCommon/RCTTurboModule.h>
#import <optional>
#import <vector>

namespace JS {
  namespace NativeShareManager {
    struct ShareOptions {
      NSString *message() const;
      NSString *tintColor() const;
      NSString *title() const;
      NSString *subtitle() const;
      NSString *url() const;
      NSString *userInterfaceStyle() const;

      ShareOptions(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeShareManager_ShareOptions)
+ (RCTManagedPointer *)JS_NativeShareManager_ShareOptions:(id)json;
@end
@protocol NativeShareManagerSpec <RCTBridgeModule, RCTTurboModule>

- (void)share:(JS::NativeShareManager::ShareOptions &)options;

@end
namespace facebook {
  namespace react {
    /**
     * ObjC++ class for module 'NativeShareManager'
     */
    class JSI_EXPORT NativeShareManagerSpecJSI : public ObjCTurboModule {
    public:
      NativeShareManagerSpecJSI(const ObjCTurboModule::InitParams &params);
    };
  } // namespace react
} // namespace facebook
inline NSString *JS::NativeShareManager::ShareOptions::message() const
{
  id const p = _v[@"message"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeShareManager::ShareOptions::tintColor() const
{
  id const p = _v[@"tintColor"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeShareManager::ShareOptions::title() const
{
  id const p = _v[@"title"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeShareManager::ShareOptions::subtitle() const
{
  id const p = _v[@"subtitle"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeShareManager::ShareOptions::url() const
{
  id const p = _v[@"url"];
  return RCTBridgingToOptionalString(p);
}
inline NSString *JS::NativeShareManager::ShareOptions::userInterfaceStyle() const
{
  id const p = _v[@"userInterfaceStyle"];
  return RCTBridgingToOptionalString(p);
}
