import { WINDOW_WIDTH, SUFFICIENT_WINDOW_WIDTH } from '@/constants/layout';

export const PROMOTION_BANNER_WIDTH = WINDOW_WIDTH - 32;
export const PROMOTION_BANNER_HEIGHT = ((SUFFICIENT_WINDOW_WIDTH - 32) / 343) * 480;
