import { SUFFICIENT_WINDOW_WIDTH } from '@/constants/layout';

export const PROMOTION_BANNER_WIDTH = SUFFICIENT_WINDOW_WIDTH - 32;
export const PROMOTION_BANNER_HEIGHT = (PROMOTION_BANNER_WIDTH / 343) * 480;
